SCHEMA_VERSION = "1.0"
SCHEMA_VERSION_KEY = "schema_version"
TAG_RULES_VERSION_KEY = "tag_rules_version"
TAG_RULES_HASH_KEY = "tag_rules_hash"
TAG_RULES_SOURCE_KEY = "tag_rules_source"

SUMMARY_SHEET = "summary"
METADATA_SHEET = "_metadata"
TRANSLATION_UNITS_SHEET = "translation_units"
TO_TRANSLATE_SHEET = "to_translate"
PREFILLED_UNITS_SHEET = "prefilled_units"
SOURCE_MAP_SHEET = "source_map"
FILLED_WORKBOOK_SHEET = "filled_workbook"
QA_REPORT_SHEET = "qa_report"
TM_PAIRS_SHEET = "tm_pairs"
TM_SOURCE_MAP_SHEET = "tm_map"
TEMPLATE_REVIEW_SHEET = "template_review"
ENTITY_CLUSTERS_SHEET = "entity_clusters"
ENTITY_STRUCTURES_SHEET = "entity_structures"
ENTITY_TERMS_SHEET = "entity_terms"
ENTITY_SOURCE_MAP_SHEET = "entity_source_map"
RELATED_UNITS_SHEET = "related_units"
NON_RELATED_UNITS_SHEET = "non_related_units"
ENTITY_MAP_SHEET = "_entity_map"

UNIT_TYPE_COLUMN = "unit_type"
SOURCE_UNIT_COLUMN = "source_unit"
TARGET_UNIT_COLUMN = "target_unit"
UNIT_ID_COLUMN = "unit_id"
COVERAGE_COUNT_COLUMN = "coverage_count"
UNIQUE_SOURCE_COUNT_COLUMN = "unique_source_count"
VARIABLES_COLUMN = "variables"
STATUS_COLUMN = "status"
SAMPLE_SOURCES_COLUMN = "sample_sources"
SAMPLE_TARGETS_COLUMN = "sample_targets"
ROW_NUMBERS_COLUMN = "row_numbers"
CONTEXT_COLUMN = "context"
TARGET_UNIT_SOURCE_COLUMN = "target_unit_source"
SUGGESTED_TARGET_UNIT_COLUMN = "suggested_target_unit"
WARNING_COLUMN = "warning"
TRANSLATOR_NOTE_COLUMN = "translator_note"
TM_ID_COLUMN = "tm_id"
ROW_NUMBER_COLUMN = "row_number"
SOURCE_COLUMN = "source"
TARGET_COLUMN = "target"
SOURCE_TEMPLATE_COLUMN = "source_template"
TARGET_TEMPLATE_COLUMN = "target_template"
VARIABLE_VALUES_COLUMN = "variable_values"
AUTO_TARGET_COLUMN = "auto_target"
EXISTING_TARGET_COLUMN = "existing_target"
FILL_STATUS_COLUMN = "fill_status"
CHECK_COLUMN = "check"
COUNT_COLUMN = "count"
KEY_COLUMN = "key"
VALUE_COLUMN = "value"
ORIGINAL_INDEX_COLUMN = "original_index"
STRUCTURE_ID_COLUMN = "structure_id"
SOURCE_STRUCTURE_COLUMN = "source_structure"
TARGET_STRUCTURE_COLUMN = "target_structure"
CONFIDENCE_COLUMN = "confidence"
RISK_COLUMN = "risk"
TERM_ID_COLUMN = "term_id"
SOURCE_ENTITY_COLUMN = "source_entity"
TARGET_ENTITY_COLUMN = "target_entity"
OCCURRENCE_COUNT_COLUMN = "occurrence_count"
STRUCTURE_IDS_COLUMN = "structure_ids"
ENTITIES_JSON_COLUMN = "entities_json"
PREVIEW_TARGET_COLUMN = "preview_target"
FILL_STATUS_COLUMN = "fill_status"

METADATA_COLUMNS = [KEY_COLUMN, VALUE_COLUMN]
TRANSLATION_UNIT_REQUIRED_COLUMNS = [
    UNIT_TYPE_COLUMN,
    SOURCE_UNIT_COLUMN,
    TARGET_UNIT_COLUMN,
]
TRANSLATION_UNIT_COLUMNS = [
    UNIT_ID_COLUMN,
    UNIT_TYPE_COLUMN,
    SOURCE_UNIT_COLUMN,
    TARGET_UNIT_COLUMN,
    COVERAGE_COUNT_COLUMN,
    UNIQUE_SOURCE_COUNT_COLUMN,
    VARIABLES_COLUMN,
    STATUS_COLUMN,
    SAMPLE_SOURCES_COLUMN,
    ROW_NUMBERS_COLUMN,
    TARGET_UNIT_SOURCE_COLUMN,
    SUGGESTED_TARGET_UNIT_COLUMN,
    WARNING_COLUMN,
    TRANSLATOR_NOTE_COLUMN,
]
TO_TRANSLATE_COLUMNS = [
    UNIT_ID_COLUMN,
    UNIT_TYPE_COLUMN,
    SOURCE_UNIT_COLUMN,
    TARGET_UNIT_COLUMN,
    SAMPLE_SOURCES_COLUMN,
    CONTEXT_COLUMN,
    ROW_NUMBER_COLUMN,
    COVERAGE_COUNT_COLUMN,
    VARIABLES_COLUMN,
    WARNING_COLUMN,
    TRANSLATOR_NOTE_COLUMN,
]
PREFILLED_UNIT_COLUMNS = [
    UNIT_ID_COLUMN,
    UNIT_TYPE_COLUMN,
    SOURCE_UNIT_COLUMN,
    TARGET_UNIT_COLUMN,
    COVERAGE_COUNT_COLUMN,
    TARGET_UNIT_SOURCE_COLUMN,
]
SOURCE_MAP_COLUMNS = [
    ROW_NUMBER_COLUMN,
    SOURCE_COLUMN,
    UNIT_ID_COLUMN,
    UNIT_TYPE_COLUMN,
    SOURCE_UNIT_COLUMN,
    VARIABLE_VALUES_COLUMN,
    TARGET_UNIT_COLUMN,
    AUTO_TARGET_COLUMN,
    EXISTING_TARGET_COLUMN,
    FILL_STATUS_COLUMN,
    WARNING_COLUMN,
]
FILLED_WORKBOOK_EXTRA_COLUMNS = [
    AUTO_TARGET_COLUMN,
    FILL_STATUS_COLUMN,
    UNIT_ID_COLUMN,
    UNIT_TYPE_COLUMN,
    WARNING_COLUMN,
]
QA_REPORT_COLUMNS = [CHECK_COLUMN, COUNT_COLUMN]
TM_PAIR_COLUMNS = [
    TM_ID_COLUMN,
    UNIT_TYPE_COLUMN,
    SOURCE_UNIT_COLUMN,
    TARGET_UNIT_COLUMN,
    COVERAGE_COUNT_COLUMN,
    UNIQUE_SOURCE_COUNT_COLUMN,
    VARIABLES_COLUMN,
    SAMPLE_SOURCES_COLUMN,
    SAMPLE_TARGETS_COLUMN,
    ROW_NUMBERS_COLUMN,
    WARNING_COLUMN,
]
TM_SOURCE_MAP_COLUMNS = [
    ROW_NUMBER_COLUMN,
    SOURCE_COLUMN,
    TARGET_COLUMN,
    UNIT_TYPE_COLUMN,
    SOURCE_UNIT_COLUMN,
    TARGET_UNIT_COLUMN,
    VARIABLE_VALUES_COLUMN,
]
TEMPLATE_REVIEW_REQUIRED_COLUMNS = [
    SOURCE_TEMPLATE_COLUMN,
    TARGET_TEMPLATE_COLUMN,
]
